yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from core.models import GenerationModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор'
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(GenerationModel):
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True
    )
    RETURN_STR = '{}, {}'

    class Meta(GenerationModel.Meta):
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.RETURN_STR.format(super().__str__(), self.group)


class Comment(GenerationModel):
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )

    class Meta(GenerationModel.Meta):
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name='Автор'
    )
    RETURN_STR = 'user={} подписан на author={}'

    class Meta():
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                fields=("author", "user",),
                name="unique_follow"
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name="self follow is not accessed"
            )
        ]

    def __str__(self):
        return self.RETURN_STR.format(
            self.user.get_username(), self.author.get_username()
        )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post, User
from posts.settings import (COUNT_POST_ON_PAGE, POST_CREATE_HTML,
                            POST_DETAIL_HTML, POST_EDIT_HTML,
                            POST_GROUP_LIST_HTML, POST_INDEX_HTML,
                            POST_PROFILE_HTML)


def page_obj(request, post_list):
    return Paginator(post_list, COUNT_POST_ON_PAGE).get_page(
        request.GET.get('page'))


def index(request):
    return render(request, POST_INDEX_HTML, {
        'page_obj': page_obj(request, Post.objects.all()),
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, POST_GROUP_LIST_HTML, {
        'group': group,
        'page_obj': page_obj(request, group.posts.all()),
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    return render(request, POST_PROFILE_HTML, {
        'author': author,
        'page_obj': page_obj(request, author.posts.all()),
        'following': Follow.objects.filter(
            user=request.user.is_authenticated,
            author=author).exists()
    })


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, POST_DETAIL_HTML, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {'form': form}
    if not form.is_valid():
        return render(request, POST_CREATE_HTML, context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, POST_EDIT_HTML, {
        'form': form,
        'is_edit': True,
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    return render(request, 'posts/follow.html', {
        'page_obj': page_obj(request, posts)
    })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user and not Follow.objects.filter(
        author=author,
        user=request.user
    ).exists():
        Follow.objects.create(author=author, user=request.user)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Страница избранных авторов
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  <div class="container py-5">
    <h3> Последние обновления на сайте </h3>
    {% cache 20 page_obj.number %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_info.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
    {% endcache %} 
  </div> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p> {{ group.description|linebreaksbr}} </p>  
    {% for post in page_obj %}
      {% include 'posts/includes/post_info.html' with not_show_group=True %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Главная страница Yatube
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with index=True %}
  <div class="container py-5">
    <h3> Последние обновления на сайте </h3>
    {% cache 20 page_obj.number %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_info.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    {% endcache %}
  </div> 
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} Редактировать пост {% else %} Новый пост {% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %} Редактировать пост {% else %} Новый пост {% endif %}
        </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data"
              {% if is_edit %}
                {% url 'posts:post_edit'  form.instance.id %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small 
                      id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }} </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: <a href="{% url 'posts:profile' post.author.username %}">  {{ post.author.get_full_name }} </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post.author.posts.count }} </span>
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">Редактировать пост</a>
      {% endif %}
      {% include 'posts/includes/comment.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя: {{ author.username }}{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <h6>Подписчиков: {{ author.following.count }} <br>
    Подписан: {{ author.follower.count }} <br>
    Комментариев: {{ author.comments.count }}</h6>
    {% if following %}
      <a class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}"
      role="button">Отписаться</a>
    {% else %}
        <a class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}"
        role="button">Подписаться</a>
    {% endif %}
    {% for post in page_obj %}
      <article>
        {% include 'posts/includes/post_info.html' %}
      </article>
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}